### ISSUE TITLE
FYI for ex3.2 Step 10-15

### ISSUE THREAD

**Issue by dmartino** [c-kobo/ui5con2023#13]
Thought I'd point it out so others may benefit from any additional information on the topic. 

Step 10 does not happen, so does the BAS editor think FilterBar type is defined?
Proceeding by manually adding the suggested fix from steps 11 and 12, additional issues come up. 
You see that taking the suggested changes, which are to add 'as unknown as FilterBar' result in some other problems.

![Screenshot 2024-04-16 121344](https://github.com/c-kobo/ui5con2023/assets/979436/4570acf2-0509-4b05-b3bf-3c24699fcd0e)

I don't know the framework well enough to understand if that will cause trouble downstream. Note that the preview does seem to work fine at this point, the Table Filter Status section updates when filters are changed.

**Comment by c-kobo** [comment]
Hi @dmartino ,
I just have seen your message and could now look into this.
I couldn't reproduce this, my test shows that adding the import FilterBarAPI in step 10 is required to get rid of the tslint issue shown:
![image](https://github.com/c-kobo/ui5con2023/assets/39270906/1ba73d3a-d171-4461-b9d8-f29e46d82cb2)

And according to your screenshot, you don't seem to be on the latest version of the hands-on, as the code snippet from step 13 deviates a bit. I've updated the exercises last month to be compliant with the latest UI5 typings.
https://github.com/c-kobo/ui5con2023/tree/main/exercises/ex3#exercise-32-add-controller-functions-for-setting-filter-status
![image](https://github.com/c-kobo/ui5con2023/assets/39270906/8d53536e-ee0e-4a09-a84d-4934260e4e43)
Could you please double check?
