### ISSUE TITLE
VS Code does not store Flexible Column Layout setting

### ISSUE THREAD

**Issue by cbsmerveguel** [c-kobo/ui5con2023#6]
Hi all,

I am developing a flexible programming model custom page application on Visual Studio Code using this tutorial. 
I have one main and one detail page which I would like to open in flexible column layout. 
However, it seem VS Code "Page Map" does not store the changes whenever it comes to changing the layout from Standard to Flexible Column.

<img width="1323" alt="Screenshot 2023-07-16 at 15 35 18" src="https://github.com/c-kobo/ui5con2023/assets/127400927/96306f35-9976-4f65-813f-9d6faa562e4e">

As I quit from and reopen the VS Code:
<img width="1328" alt="Screenshot 2023-07-16 at 15 35 36" src="https://github.com/c-kobo/ui5con2023/assets/127400927/a90a12de-9d92-4527-bb90-e9675de90af8">

Could that be a bug? I appreciate it if you could kindly share how can I pass this issue?

Best,
Merve

**Comment by c-kobo** [comment]
This should be working. Does the app start correctly? Would it be possible that you share the manifest.json of the app so that I can check whether the configuration is correct? Please also check the output tab whether any errors are shown for the app modeller.

**Comment by cbsmerveguel** [comment]
Thanks for your prompt reply Christian. Please find the manifest.json as follows. I double checked the output tab, there is no error.

[manifestjson.docx](https://github.com/c-kobo/ui5con2023/files/12064867/manifestjson.docx)

< Replaced the explicit manifest.json with attached one (same content) >

**Comment by c-kobo** [comment]
Thank you for sharing. The manifest looks good, though it doesn’t have the fcl configuration. I’ll involve the Fiori Tools colleagues so they can comment on this.

**Comment by 815are** [comment]
@cbsmerveguel

Could you please share/attach your app?

**Comment by cbsmerveguel** [comment]
Hi @c-kobo, 

Kindly find as attached.

[task-management_copy.zip](https://github.com/c-kobo/ui5con2023/files/12067177/task-management_copy.zip)

Best,
Merve

**Comment by 815are** [comment]
@cbsmerveguel 

Thank you for attached app, but we can not reproduce issue with your given app.
Could you please provide some additional information?:
1. What OS you are using, is it MacOS, Windows, etc.?
2. Could you please provide full local path to project's app folder?, like `C:\test-projects\issues\fcl6\task-management_copy\app\task-processing-custom-ts`

**Comment by cbsmerveguel** [comment]
Hi @815are,

Sorry for neglecting to mention you in my previous message. 

I believe I found something. Before I share the project with you, I deleted a separate dummy app in the project as it was idle and contains almost no configuration/coding. As you said you could not reproduce the issue, I went back to my repo (still without the dummy app), then do the  Flexible Column Layout change again, in this case the FCL change was stored fine without any problem.
 
As I re-added the dummy app back again, the storing functionality stopped working.

Please find the project as attached this time with the dummy project.

1. OS: MacOS - Ventura 13.4.1   
2. /Users/me/Documents/GitProjects/TaskManagement/task-management

[task-management copy.zip](https://github.com/c-kobo/ui5con2023/files/12068490/task-management.copy.zip)

**Comment by 815are** [comment]
Hi @cbsmerveguel 

thanks for your attached app, we can reproduce and identified issue and we are working on fix.
Prerequisite for issue is app names, app names like `task-processing-custom` and `task-processing-custom-ts`.
Prerequisite is that `task-processing-custom-ts` starts with `task-processing-custom` and currently it gives unexpected behaviour.

While fix is not released, could you please rename `task-processing-custom` to something like `task-processing-custom-js`?
Please note that multiple places should be renames:
![image](https://github.com/c-kobo/ui5con2023/assets/90789422/d370cc08-d58a-4014-9995-873b1580da36)

Attaching project with renamed references:
[task-management copy-renamed.zip](https://github.com/c-kobo/ui5con2023/files/12069077/task-management.copy-renamed.zip)

**Comment by cbsmerveguel** [comment]
Hi @815are,

Thank you for your prompt return. I can do the renaming, no problem. 

Happy to help,
Best,

Merve

**Comment by c-kobo** [comment]
Thanks for bringing this up. Closing this as the issue has been adressed, and a fix is in preparation.
