### ISSUE TITLE
Fiori Tools: Page Map does not open

### ISSUE THREAD

**Issue by BenReim** [c-kobo/ui5con2023#8]
Thanks for this in-depth tutorial! 

**Issue**
I was trying to follow the steps, but face an error when trying to open the `Page Map` through the `Application Info`: 
```shell
EntryNotFound (FileSystemError): ftfs:/home/user/projects/ui5con2023/app/managetravels/src/app.json
```

**Context**:
* SAP Business Application Studio Version: 1.79.2
* App Generator@sap/generator-fiori-elements Version1.10.4

**Comment by c-kobo** [comment]
hi @BenReim, I'll check with the Tools colleagues on this and get back to you.

**Comment by cfg74** [comment]
Hi @BenReim , PO of Application Modeler here. The error you see can indicate that the `@sap/ux-specification` node package is not installed or not properly loaded. Can you check whether reload (browser refresh) of the BAS devspace solves the issue? If not, does the App info page show red messages in the Status part? If yes, please execute the offered commands.

If everything shows green, there might be an unexpected problem with parsing the service metadata. Please open the "Output" panel and select "SAP Fiori tools - Application Modeler", and check for error message. Please post the output here.

**Comment by BenReim** [comment]
Hi @cfg74, thanks for reaching out! In the meantime, I can't reproduce this issue anymore.

I think you are right with suspecting an install issue related to `@sap/ux-specification` - and did a clean `npm i` and everything works fine now. The App Info pages opens and the status is green 👍
